name: ci

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build
        run: bash docker_build_create_start.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: libs
          path: ./swiftshader-android.zip
